package com.uchung.departmentappraise.mapper;

import com.github.pagehelper.Page;
import com.uchung.departmentappraise.model.Personnel;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;
@Mapper
@Component("personnelMapper")
public interface PersonnelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated
     */
    int insert(Personnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated
     */
    Personnel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated
     */
    List<Personnel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personnel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Personnel record);

    /**
     * 分页查询信息
     * @return
     */
    Page<Personnel> getAllPage();

    List<Personnel> selectAllByStatus(boolean status);
}